# Generated by Django 5.2.16 on 2026-07-18 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('receive_sms', models.BooleanField(default=True)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_push', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('BADGE', 'Badge'), ('CERTIFICATE', 'Certificate'), ('PRIZE', 'Prize'), ('PRIVILEGE', 'Privilege'), ('RECOGNITION', 'Public Recognition'), ('OTHER', 'Other')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fa-trophy', max_length=50)),
                ('color', models.CharField(default='#f59e0b', help_text='Hex color code', max_length=20)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.school')),
            ],
            options={
                'ordering': ['points_required', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('CLASS_TEACHER', 'Class Teacher'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('COUNSELOR', 'Counselor'), ('LIBRARIAN', 'Librarian'), ('NURSE', 'School Nurse')], max_length=30)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions JSON')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Roles',
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('checkin_method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('NFC', 'NFC Card'), ('MANUAL', 'Manual Entry'), ('BIOMETRIC', 'Biometric')], default='MANUAL', max_length=20)),
                ('qr_code_data', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['student', 'date'], name='core_attend_student_1db04d_idx'), models.Index(fields=['stream', 'date'], name='core_attend_stream__7a3a1a_idx'), models.Index(fields=['status', 'date'], name='core_attend_status_14f160_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REPORT_CARD', 'Report Card'), ('TRANSFER_LETTER', 'Transfer Letter'), ('MEDICAL_RECORD', 'Medical Record'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO_ID', 'Photo ID'), ('PARENT_ID', 'Parent/Guardian ID'), ('DISCIPLINE_RECORD', 'Discipline Record'), ('ACADEMIC_TRANSCRIPT', 'Academic Transcript'), ('AWARD_CERTIFICATE', 'Award Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='core.documentvault')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='core_docume_student_7612d2_idx'), models.Index(fields=['is_confidential', 'created_at'], name='core_docume_is_conf_89d36e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('TERMLY', 'Termly'), ('YEARLY', 'Yearly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('points_delta', models.IntegerField(default=0, help_text='Change from previous period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='core.student')),
            ],
            options={
                'ordering': ['-total_points', 'rank'],
                'indexes': [models.Index(fields=['school', 'period', '-total_points'], name='core_leader_school__a9e3d4_idx')],
                'unique_together': {('student', 'period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='StudentParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='Parent/Guardian', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='core.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.student')),
            ],
            options={
                'ordering': ['-is_primary'],
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(choices=[('DISCIPLINE_REPORT', 'Discipline Report'), ('POSITIVE_BEHAVIOR', 'Positive Behavior'), ('INTERVENTION_SUCCESS', 'Intervention Success'), ('PERFECT_ATTENDANCE', 'Perfect Attendance'), ('ACADEMIC_EXCELLENCE', 'Academic Excellence'), ('LEADERSHIP', 'Leadership'), ('COMMUNITY_SERVICE', 'Community Service'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('PENALTY', 'Penalty Deduction')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_awarded', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplinereport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='core_studen_student_b95b4b_idx'), models.Index(fields=['reason', 'created_at'], name='core_studen_reason_9a5f76_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_awarded', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_earnings', to='core.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_earned', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'reward', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'indexes': [models.Index(fields=['stream', 'form', 'day'], name='core_timeta_stream__5c1ad6_idx'), models.Index(fields=['teacher', 'day', 'start_time'], name='core_timeta_teacher_d0c659_idx')],
            },
        ),
    ]
