# Generated by Django 5.2.16 on 2026-07-19 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentprofile_reward_subject_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_by_role', models.CharField(blank=True, help_text='STUDENT / PARENT / GUARDIAN', max_length=20)),
                ('reason', models.TextField(help_text='Why the report is being disputed')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('UPHELD', 'Upheld (report stands)'), ('Overturned', 'Overturned (report reversed)'), ('PARTIALLY_UPHELD', 'Partially Upheld'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('LETTER', 'Physical Letter')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('consent_given', models.BooleanField(default=False, help_text='Parent opted in to this channel')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='SENT', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False, help_text='True if this hit an anomaly threshold')),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('RESOLVE', 'Resolved'), ('DELETE', 'Deleted (soft)'), ('RESTORE', 'Restored')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Field values at time of change')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('DETENTION', 'Detention'), ('COMMUNITY_SERVICE', 'Community Service'), ('SUSPENSION', 'Suspension'), ('COUNSELING', 'Counseling'), ('PARENT_MEETING', 'Parent Meeting'), ('WARNING_LETTER', 'Warning Letter'), ('OTHER', 'Other')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='intervention_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Set true for critical/serious reports that need a second sign-off'),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['approval_status'], name='core_discip_approva_e8b170_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['is_resolved'], name='core_discip_is_reso_36142c_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['requires_approval'], name='core_discip_require_dac174_idx'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.disciplinereport'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.student'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.parentprofile'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.disciplinereport'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.student'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_logs', to='core.student'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.disciplinereport'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sanctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sanctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.disciplinereport'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status'], name='core_appeal_status_5dc7db_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['student', 'status'], name='core_appeal_student_64382d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['student', 'sent_at'], name='core_commun_student_2ebcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['channel'], name='core_commun_channel_3c9671_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['reported_by', 'reported_at'], name='core_rateli_reporte_e949e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['student', 'reported_at'], name='core_rateli_student_2c04f9_idx'),
        ),
        migrations.AddIndex(
            model_name='reporthistory',
            index=models.Index(fields=['report', 'changed_at'], name='core_report_report__cca7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='reporthistory',
            index=models.Index(fields=['action'], name='core_report_action_b0fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['student', 'status'], name='core_sancti_student_a7c5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['scheduled_date'], name='core_sancti_schedul_30a383_idx'),
        ),
    ]
