# Generated by Django 5.2.16 on 2026-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appeal_communicationlog_ratelimitlog_reporthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
